## Importing Libraries

In [12]:
import numpy as np
import pandas as pd

## Importing Dataset

In [13]:
df = pd.read_csv(r'C:\Users\DELL\Downloads\ecommerce_messy_dataset.csv')
df.head()

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,payment_method,customer_age,rating,return_flag,shipping_city
0,ORD001382,CUST00230,PROD0156,10-17-2022,22:51:03,West,Beauty,9,399.15,7.8,Credit Card,35.0,3.1,No,DALLAS
1,ORD001002,CUST00176,PROD0197,24/09/2023,13:43:20,Central,home & garden,8,105.48,16.0,Bank Transfer,38.0,1.9,Yes,Phoenix
2,ORD002682,CUST00138,PROD0103,2022/11/01,08:34:16,East,Electronics,4,587.89,37.5,Credit Card,44.0,2.5,No,MIAMI
3,ORD002322,NaN,PROD0178,10-02-2023,13:36:06,Central,Home & Garden,5,198.49,28.6,Bank Transfer,72.0,1.5,No,Phoenix
4,ORD001669,CUST00188,PROD0178,14/05/2023,19:32:47,South,Beauty,2,-50.0,33.2,Cash,52.0,3.6,No,Los Angeles

In [15]:
df

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,payment_method,customer_age,rating,return_flag,shipping_city
0,ORD001382,CUST00230,PROD0156,10-17-2022,22:51:03,West,Beauty,9,399.15,7.8,Credit Card,35.0,3.1,No,DALLAS
1,ORD001002,CUST00176,PROD0197,24/09/2023,13:43:20,Central,home & garden,8,105.48,16.0,Bank Transfer,38.0,1.9,Yes,Phoenix
2,ORD002682,CUST00138,PROD0103,2022/11/01,08:34:16,East,Electronics,4,587.89,37.5,Credit Card,44.0,2.5,No,MIAMI
3,ORD002322,NaN,PROD0178,10-02-2023,13:36:06,Central,Home & Garden,5,198.49,28.6,Bank Transfer,72.0,1.5,No,Phoenix
4,ORD001669,CUST00188,PROD0178,14/05/2023,19:32:47,South,Beauty,2,-50.0,33.2,Cash,52.0,3.6,No,Los Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ORD002737,CUST00163,PROD0056,05-14-2022,20:21:10,North,Beauty,10,$198.11,5.9,Debit Card,64.0,1.4,Yes,Miami
1816,ORD002192,CUST00327,PROD0096,04-10-2023,06:31:30,North,Toys,1,285,36.1,Cash,67.0,NaN,No,New York
1817,ORD002209,CUST00420,PROD0037,22/02/2023,15:17:47,East,Clothing,10,66.59,33.1,Bank Transfer,72.0,3.8,No,Phoenix
1818,ORD002059,CUST00238,PROD0113,13/02/2023,13:03:13,West,CLOTHING,3,20,28.6,Debit Card,59.0,1.7,Yes,New York
1819,ORD001641,CUST00283,PROD0123,2022/06/10,11:46:48,East,Home & Garden,2,347.83,11.8,Debit Card,57.0,1.2,No,Atlanta

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1820 entries, 0 to 1819
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        1820 non-null   object
 1   customer_id     1760 non-null   object
 2   product_id      1820 non-null   object
 3   order_date      1820 non-null   object
 4   order_time      1820 non-null   object
 5   region          1753 non-null   object
 6   category        1764 non-null   object
 7   quantity        1820 non-null   int64
 8   unit_price      1820 non-null   object
 9   discount_pct    1740 non-null   float64
 10  payment_method  1761 non-null   object
 11  customer_age    1746 non-null   float64
 12  rating          1716 non-null   float64
 13  return_flag     1820 non-null   object
 14  shipping_city   1820 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 213.4+ KB

## Filling Missing Values

In [16]:
df['customer_id'].fillna('Unknown', inplace=True)
df['region'].fillna('Unknown', inplace=True)
df['category'].fillna('Unknown', inplace=True)
df['payment_method'].fillna('Unknown', inplace=True)

df['customer_age'].fillna(df['customer_age'].median(), inplace=True)
df['rating'].fillna(df['rating'].mean(), inplace=True)
df['discount_pct'].fillna(0, inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_8224\3997842112.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['customer_id'].fillna('Unknown', inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_8224\3997842112.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['region'].fillna('Unknown', inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_8224\3997842112.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['category'].fillna('Unknown', inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_8224\3997842112.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['payment_method'].fillna('Unknown', inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_8224\3997842112.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['customer_age'].fillna(df['customer_age'].median(), inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_8224\3997842112.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['rating'].fillna(df['rating'].mean(), inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_8224\3997842112.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['discount_pct'].fillna(0, inplace=True)

In [17]:
df

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,payment_method,customer_age,rating,return_flag,shipping_city
0,ORD001382,CUST00230,PROD0156,10-17-2022,22:51:03,West,Beauty,9,399.15,7.8,Credit Card,35.0,3.100000,No,DALLAS
1,ORD001002,CUST00176,PROD0197,24/09/2023,13:43:20,Central,home & garden,8,105.48,16.0,Bank Transfer,38.0,1.900000,Yes,Phoenix
2,ORD002682,CUST00138,PROD0103,2022/11/01,08:34:16,East,Electronics,4,587.89,37.5,Credit Card,44.0,2.500000,No,MIAMI
3,ORD002322,Unknown,PROD0178,10-02-2023,13:36:06,Central,Home & Garden,5,198.49,28.6,Bank Transfer,72.0,1.500000,No,Phoenix
4,ORD001669,CUST00188,PROD0178,14/05/2023,19:32:47,South,Beauty,2,-50.0,33.2,Cash,52.0,3.600000,No,Los Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ORD002737,CUST00163,PROD0056,05-14-2022,20:21:10,North,Beauty,10,$198.11,5.9,Debit Card,64.0,1.400000,Yes,Miami
1816,ORD002192,CUST00327,PROD0096,04-10-2023,06:31:30,North,Toys,1,285,36.1,Cash,67.0,3.670571,No,New York
1817,ORD002209,CUST00420,PROD0037,22/02/2023,15:17:47,East,Clothing,10,66.59,33.1,Bank Transfer,72.0,3.800000,No,Phoenix
1818,ORD002059,CUST00238,PROD0113,13/02/2023,13:03:13,West,CLOTHING,3,20,28.6,Debit Card,59.0,1.700000,Yes,New York
1819,ORD001641,CUST00283,PROD0123,2022/06/10,11:46:48,East,Home & Garden,2,347.83,11.8,Debit Card,57.0,1.200000,No,Atlanta

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1820 entries, 0 to 1819
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        1820 non-null   object
 1   customer_id     1820 non-null   object
 2   product_id      1820 non-null   object
 3   order_date      1820 non-null   object
 4   order_time      1820 non-null   object
 5   region          1820 non-null   object
 6   category        1820 non-null   object
 7   quantity        1820 non-null   int64
 8   unit_price      1820 non-null   object
 9   discount_pct    1820 non-null   float64
 10  payment_method  1820 non-null   object
 11  customer_age    1820 non-null   float64
 12  rating          1820 non-null   float64
 13  return_flag     1820 non-null   object
 14  shipping_city   1820 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 213.4+ KB

In [19]:
print(df['customer_age'].median())
print(df['rating'].mean())

47.0
3.6705710955710957

## Correcting Unit Price Datatype

In [21]:
df['unit_price'] = (
    df['unit_price']
    .astype(str)
    .str.replace(',', '')  # remove commas first
    .str.replace('[^0-9.]', '', regex=True)
)

df['unit_price'] = pd.to_numeric(df['unit_price'], errors='coerce')

In [22]:
df['unit_price'].dtype
df['unit_price'].head()

0    399.15
1    105.48
2    587.89
3    198.49
4     50.00
Name: unit_price, dtype: float64

In [24]:
df

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,payment_method,customer_age,rating,return_flag,shipping_city
0,ORD001382,CUST00230,PROD0156,10-17-2022,22:51:03,West,Beauty,9,399.15,7.8,Credit Card,35.0,3.100000,No,DALLAS
1,ORD001002,CUST00176,PROD0197,24/09/2023,13:43:20,Central,home & garden,8,105.48,16.0,Bank Transfer,38.0,1.900000,Yes,Phoenix
2,ORD002682,CUST00138,PROD0103,2022/11/01,08:34:16,East,Electronics,4,587.89,37.5,Credit Card,44.0,2.500000,No,MIAMI
3,ORD002322,Unknown,PROD0178,10-02-2023,13:36:06,Central,Home & Garden,5,198.49,28.6,Bank Transfer,72.0,1.500000,No,Phoenix
4,ORD001669,CUST00188,PROD0178,14/05/2023,19:32:47,South,Beauty,2,50.00,33.2,Cash,52.0,3.600000,No,Los Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ORD002737,CUST00163,PROD0056,05-14-2022,20:21:10,North,Beauty,10,198.11,5.9,Debit Card,64.0,1.400000,Yes,Miami
1816,ORD002192,CUST00327,PROD0096,04-10-2023,06:31:30,North,Toys,1,285.00,36.1,Cash,67.0,3.670571,No,New York
1817,ORD002209,CUST00420,PROD0037,22/02/2023,15:17:47,East,Clothing,10,66.59,33.1,Bank Transfer,72.0,3.800000,No,Phoenix
1818,ORD002059,CUST00238,PROD0113,13/02/2023,13:03:13,West,CLOTHING,3,20.00,28.6,Debit Card,59.0,1.700000,Yes,New York
1819,ORD001641,CUST00283,PROD0123,2022/06/10,11:46:48,East,Home & Garden,2,347.83,11.8,Debit Card,57.0,1.200000,No,Atlanta

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1820 entries, 0 to 1819
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        1820 non-null   object
 1   customer_id     1820 non-null   object
 2   product_id      1820 non-null   object
 3   order_date      1820 non-null   object
 4   order_time      1820 non-null   object
 5   region          1820 non-null   object
 6   category        1820 non-null   object
 7   quantity        1820 non-null   int64
 8   unit_price      1820 non-null   float64
 9   discount_pct    1820 non-null   float64
 10  payment_method  1820 non-null   object
 11  customer_age    1820 non-null   float64
 12  rating          1820 non-null   float64
 13  return_flag     1820 non-null   object
 14  shipping_city   1820 non-null   object
dtypes: float64(4), int64(1), object(10)
memory usage: 213.4+ KB

## Correcting Order_date & Order_time Datatypes

In [28]:
df['order_date'].isnull().sum()
df['order_time'].isnull().sum()

0

In [29]:
df['order_date'] = df['order_date'].astype(str).str.strip()
df['order_time'] = df['order_time'].astype(str).str.strip()

In [30]:
df

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,payment_method,customer_age,rating,return_flag,shipping_city
0,ORD001382,CUST00230,PROD0156,10-17-2022,22:51:03,West,Beauty,9,399.15,7.8,Credit Card,35.0,3.100000,No,DALLAS
1,ORD001002,CUST00176,PROD0197,24/09/2023,13:43:20,Central,home & garden,8,105.48,16.0,Bank Transfer,38.0,1.900000,Yes,Phoenix
2,ORD002682,CUST00138,PROD0103,2022/11/01,08:34:16,East,Electronics,4,587.89,37.5,Credit Card,44.0,2.500000,No,MIAMI
3,ORD002322,Unknown,PROD0178,10-02-2023,13:36:06,Central,Home & Garden,5,198.49,28.6,Bank Transfer,72.0,1.500000,No,Phoenix
4,ORD001669,CUST00188,PROD0178,14/05/2023,19:32:47,South,Beauty,2,50.00,33.2,Cash,52.0,3.600000,No,Los Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ORD002737,CUST00163,PROD0056,05-14-2022,20:21:10,North,Beauty,10,198.11,5.9,Debit Card,64.0,1.400000,Yes,Miami
1816,ORD002192,CUST00327,PROD0096,04-10-2023,06:31:30,North,Toys,1,285.00,36.1,Cash,67.0,3.670571,No,New York
1817,ORD002209,CUST00420,PROD0037,22/02/2023,15:17:47,East,Clothing,10,66.59,33.1,Bank Transfer,72.0,3.800000,No,Phoenix
1818,ORD002059,CUST00238,PROD0113,13/02/2023,13:03:13,West,CLOTHING,3,20.00,28.6,Debit Card,59.0,1.700000,Yes,New York
1819,ORD001641,CUST00283,PROD0123,2022/06/10,11:46:48,East,Home & Garden,2,347.83,11.8,Debit Card,57.0,1.200000,No,Atlanta

In [31]:
def clean_date(date):
    try:
        return pd.to_datetime(date, format='%Y/%m/%d')
    except:
        try:
            return pd.to_datetime(date, format='%d/%m/%Y')
        except:
            try:
                return pd.to_datetime(date, format='%m-%d-%Y')
            except:
                return pd.NaT

df['order_date_clean'] = df['order_date'].apply(clean_date)

In [32]:
df

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,payment_method,customer_age,rating,return_flag,shipping_city,order_date_clean
0,ORD001382,CUST00230,PROD0156,10-17-2022,22:51:03,West,Beauty,9,399.15,7.8,Credit Card,35.0,3.100000,No,DALLAS,2022-10-17
1,ORD001002,CUST00176,PROD0197,24/09/2023,13:43:20,Central,home & garden,8,105.48,16.0,Bank Transfer,38.0,1.900000,Yes,Phoenix,2023-09-24
2,ORD002682,CUST00138,PROD0103,2022/11/01,08:34:16,East,Electronics,4,587.89,37.5,Credit Card,44.0,2.500000,No,MIAMI,2022-11-01
3,ORD002322,Unknown,PROD0178,10-02-2023,13:36:06,Central,Home & Garden,5,198.49,28.6,Bank Transfer,72.0,1.500000,No,Phoenix,2023-10-02
4,ORD001669,CUST00188,PROD0178,14/05/2023,19:32:47,South,Beauty,2,50.00,33.2,Cash,52.0,3.600000,No,Los Angeles,2023-05-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ORD002737,CUST00163,PROD0056,05-14-2022,20:21:10,North,Beauty,10,198.11,5.9,Debit Card,64.0,1.400000,Yes,Miami,2022-05-14
1816,ORD002192,CUST00327,PROD0096,04-10-2023,06:31:30,North,Toys,1,285.00,36.1,Cash,67.0,3.670571,No,New York,2023-04-10
1817,ORD002209,CUST00420,PROD0037,22/02/2023,15:17:47,East,Clothing,10,66.59,33.1,Bank Transfer,72.0,3.800000,No,Phoenix,2023-02-22
1818,ORD002059,CUST00238,PROD0113,13/02/2023,13:03:13,West,CLOTHING,3,20.00,28.6,Debit Card,59.0,1.700000,Yes,New York,2023-02-13
1819,ORD001641,CUST00283,PROD0123,2022/06/10,11:46:48,East,Home & Garden,2,347.83,11.8,Debit Card,57.0,1.200000,No,Atlanta,2022-06-10

In [33]:
df['order_datetime'] = pd.to_datetime(
    df['order_date_clean'].astype(str) + ' ' + df['order_time']
)

In [34]:
df

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,payment_method,customer_age,rating,return_flag,shipping_city,order_date_clean,order_datetime
0,ORD001382,CUST00230,PROD0156,10-17-2022,22:51:03,West,Beauty,9,399.15,7.8,Credit Card,35.0,3.100000,No,DALLAS,2022-10-17,2022-10-17 22:51:03
1,ORD001002,CUST00176,PROD0197,24/09/2023,13:43:20,Central,home & garden,8,105.48,16.0,Bank Transfer,38.0,1.900000,Yes,Phoenix,2023-09-24,2023-09-24 13:43:20
2,ORD002682,CUST00138,PROD0103,2022/11/01,08:34:16,East,Electronics,4,587.89,37.5,Credit Card,44.0,2.500000,No,MIAMI,2022-11-01,2022-11-01 08:34:16
3,ORD002322,Unknown,PROD0178,10-02-2023,13:36:06,Central,Home & Garden,5,198.49,28.6,Bank Transfer,72.0,1.500000,No,Phoenix,2023-10-02,2023-10-02 13:36:06
4,ORD001669,CUST00188,PROD0178,14/05/2023,19:32:47,South,Beauty,2,50.00,33.2,Cash,52.0,3.600000,No,Los Angeles,2023-05-14,2023-05-14 19:32:47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ORD002737,CUST00163,PROD0056,05-14-2022,20:21:10,North,Beauty,10,198.11,5.9,Debit Card,64.0,1.400000,Yes,Miami,2022-05-14,2022-05-14 20:21:10
1816,ORD002192,CUST00327,PROD0096,04-10-2023,06:31:30,North,Toys,1,285.00,36.1,Cash,67.0,3.670571,No,New York,2023-04-10,2023-04-10 06:31:30
1817,ORD002209,CUST00420,PROD0037,22/02/2023,15:17:47,East,Clothing,10,66.59,33.1,Bank Transfer,72.0,3.800000,No,Phoenix,2023-02-22,2023-02-22 15:17:47
1818,ORD002059,CUST00238,PROD0113,13/02/2023,13:03:13,West,CLOTHING,3,20.00,28.6,Debit Card,59.0,1.700000,Yes,New York,2023-02-13,2023-02-13 13:03:13
1819,ORD001641,CUST00283,PROD0123,2022/06/10,11:46:48,East,Home & Garden,2,347.83,11.8,Debit Card,57.0,1.200000,No,Atlanta,2022-06-10,2022-06-10 11:46:48

In [35]:
df['year'] = df['order_datetime'].dt.year
df['month'] = df['order_datetime'].dt.month
df['day'] = df['order_datetime'].dt.day
df['hour'] = df['order_datetime'].dt.hour

In [36]:
df

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,...,customer_age,rating,return_flag,shipping_city,order_date_clean,order_datetime,year,month,day,hour
0,ORD001382,CUST00230,PROD0156,10-17-2022,22:51:03,West,Beauty,9,399.15,7.8,...,35.0,3.100000,No,DALLAS,2022-10-17,2022-10-17 22:51:03,2022,10,17,22
1,ORD001002,CUST00176,PROD0197,24/09/2023,13:43:20,Central,home & garden,8,105.48,16.0,...,38.0,1.900000,Yes,Phoenix,2023-09-24,2023-09-24 13:43:20,2023,9,24,13
2,ORD002682,CUST00138,PROD0103,2022/11/01,08:34:16,East,Electronics,4,587.89,37.5,...,44.0,2.500000,No,MIAMI,2022-11-01,2022-11-01 08:34:16,2022,11,1,8
3,ORD002322,Unknown,PROD0178,10-02-2023,13:36:06,Central,Home & Garden,5,198.49,28.6,...,72.0,1.500000,No,Phoenix,2023-10-02,2023-10-02 13:36:06,2023,10,2,13
4,ORD001669,CUST00188,PROD0178,14/05/2023,19:32:47,South,Beauty,2,50.00,33.2,...,52.0,3.600000,No,Los Angeles,2023-05-14,2023-05-14 19:32:47,2023,5,14,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ORD002737,CUST00163,PROD0056,05-14-2022,20:21:10,North,Beauty,10,198.11,5.9,...,64.0,1.400000,Yes,Miami,2022-05-14,2022-05-14 20:21:10,2022,5,14,20
1816,ORD002192,CUST00327,PROD0096,04-10-2023,06:31:30,North,Toys,1,285.00,36.1,...,67.0,3.670571,No,New York,2023-04-10,2023-04-10 06:31:30,2023,4,10,6
1817,ORD002209,CUST00420,PROD0037,22/02/2023,15:17:47,East,Clothing,10,66.59,33.1,...,72.0,3.800000,No,Phoenix,2023-02-22,2023-02-22 15:17:47,2023,2,22,15
1818,ORD002059,CUST00238,PROD0113,13/02/2023,13:03:13,West,CLOTHING,3,20.00,28.6,...,59.0,1.700000,Yes,New York,2023-02-13,2023-02-13 13:03:13,2023,2,13,13
1819,ORD001641,CUST00283,PROD0123,2022/06/10,11:46:48,East,Home & Garden,2,347.83,11.8,...,57.0,1.200000,No,Atlanta,2022-06-10,2022-06-10 11:46:48,2022,6,10,11

## Standardizing Shipping_city letter case

In [37]:
df['shipping_city'] = df['shipping_city'].str.title()

In [38]:
df

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,...,customer_age,rating,return_flag,shipping_city,order_date_clean,order_datetime,year,month,day,hour
0,ORD001382,CUST00230,PROD0156,10-17-2022,22:51:03,West,Beauty,9,399.15,7.8,...,35.0,3.100000,No,Dallas,2022-10-17,2022-10-17 22:51:03,2022,10,17,22
1,ORD001002,CUST00176,PROD0197,24/09/2023,13:43:20,Central,home & garden,8,105.48,16.0,...,38.0,1.900000,Yes,Phoenix,2023-09-24,2023-09-24 13:43:20,2023,9,24,13
2,ORD002682,CUST00138,PROD0103,2022/11/01,08:34:16,East,Electronics,4,587.89,37.5,...,44.0,2.500000,No,Miami,2022-11-01,2022-11-01 08:34:16,2022,11,1,8
3,ORD002322,Unknown,PROD0178,10-02-2023,13:36:06,Central,Home & Garden,5,198.49,28.6,...,72.0,1.500000,No,Phoenix,2023-10-02,2023-10-02 13:36:06,2023,10,2,13
4,ORD001669,CUST00188,PROD0178,14/05/2023,19:32:47,South,Beauty,2,50.00,33.2,...,52.0,3.600000,No,Los Angeles,2023-05-14,2023-05-14 19:32:47,2023,5,14,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ORD002737,CUST00163,PROD0056,05-14-2022,20:21:10,North,Beauty,10,198.11,5.9,...,64.0,1.400000,Yes,Miami,2022-05-14,2022-05-14 20:21:10,2022,5,14,20
1816,ORD002192,CUST00327,PROD0096,04-10-2023,06:31:30,North,Toys,1,285.00,36.1,...,67.0,3.670571,No,New York,2023-04-10,2023-04-10 06:31:30,2023,4,10,6
1817,ORD002209,CUST00420,PROD0037,22/02/2023,15:17:47,East,Clothing,10,66.59,33.1,...,72.0,3.800000,No,Phoenix,2023-02-22,2023-02-22 15:17:47,2023,2,22,15
1818,ORD002059,CUST00238,PROD0113,13/02/2023,13:03:13,West,CLOTHING,3,20.00,28.6,...,59.0,1.700000,Yes,New York,2023-02-13,2023-02-13 13:03:13,2023,2,13,13
1819,ORD001641,CUST00283,PROD0123,2022/06/10,11:46:48,East,Home & Garden,2,347.83,11.8,...,57.0,1.200000,No,Atlanta,2022-06-10,2022-06-10 11:46:48,2022,6,10,11

## Standardizing Category & Region letter case

In [39]:
df['category'] = df['category'].str.strip().str.title()
df['region'] = df['region'].str.strip().str.title()

In [40]:
df

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,...,customer_age,rating,return_flag,shipping_city,order_date_clean,order_datetime,year,month,day,hour
0,ORD001382,CUST00230,PROD0156,10-17-2022,22:51:03,West,Beauty,9,399.15,7.8,...,35.0,3.100000,No,Dallas,2022-10-17,2022-10-17 22:51:03,2022,10,17,22
1,ORD001002,CUST00176,PROD0197,24/09/2023,13:43:20,Central,Home & Garden,8,105.48,16.0,...,38.0,1.900000,Yes,Phoenix,2023-09-24,2023-09-24 13:43:20,2023,9,24,13
2,ORD002682,CUST00138,PROD0103,2022/11/01,08:34:16,East,Electronics,4,587.89,37.5,...,44.0,2.500000,No,Miami,2022-11-01,2022-11-01 08:34:16,2022,11,1,8
3,ORD002322,Unknown,PROD0178,10-02-2023,13:36:06,Central,Home & Garden,5,198.49,28.6,...,72.0,1.500000,No,Phoenix,2023-10-02,2023-10-02 13:36:06,2023,10,2,13
4,ORD001669,CUST00188,PROD0178,14/05/2023,19:32:47,South,Beauty,2,50.00,33.2,...,52.0,3.600000,No,Los Angeles,2023-05-14,2023-05-14 19:32:47,2023,5,14,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ORD002737,CUST00163,PROD0056,05-14-2022,20:21:10,North,Beauty,10,198.11,5.9,...,64.0,1.400000,Yes,Miami,2022-05-14,2022-05-14 20:21:10,2022,5,14,20
1816,ORD002192,CUST00327,PROD0096,04-10-2023,06:31:30,North,Toys,1,285.00,36.1,...,67.0,3.670571,No,New York,2023-04-10,2023-04-10 06:31:30,2023,4,10,6
1817,ORD002209,CUST00420,PROD0037,22/02/2023,15:17:47,East,Clothing,10,66.59,33.1,...,72.0,3.800000,No,Phoenix,2023-02-22,2023-02-22 15:17:47,2023,2,22,15
1818,ORD002059,CUST00238,PROD0113,13/02/2023,13:03:13,West,Clothing,3,20.00,28.6,...,59.0,1.700000,Yes,New York,2023-02-13,2023-02-13 13:03:13,2023,2,13,13
1819,ORD001641,CUST00283,PROD0123,2022/06/10,11:46:48,East,Home & Garden,2,347.83,11.8,...,57.0,1.200000,No,Atlanta,2022-06-10,2022-06-10 11:46:48,2022,6,10,11

## Normalizing Return flag values

In [41]:
df['normalized_return_flag'] = df['return_flag'].map({'Yes': 1, 'No': 0})

In [42]:
df

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,...,rating,return_flag,shipping_city,order_date_clean,order_datetime,year,month,day,hour,normalized_return_flag
0,ORD001382,CUST00230,PROD0156,10-17-2022,22:51:03,West,Beauty,9,399.15,7.8,...,3.100000,No,Dallas,2022-10-17,2022-10-17 22:51:03,2022,10,17,22,0
1,ORD001002,CUST00176,PROD0197,24/09/2023,13:43:20,Central,Home & Garden,8,105.48,16.0,...,1.900000,Yes,Phoenix,2023-09-24,2023-09-24 13:43:20,2023,9,24,13,1
2,ORD002682,CUST00138,PROD0103,2022/11/01,08:34:16,East,Electronics,4,587.89,37.5,...,2.500000,No,Miami,2022-11-01,2022-11-01 08:34:16,2022,11,1,8,0
3,ORD002322,Unknown,PROD0178,10-02-2023,13:36:06,Central,Home & Garden,5,198.49,28.6,...,1.500000,No,Phoenix,2023-10-02,2023-10-02 13:36:06,2023,10,2,13,0
4,ORD001669,CUST00188,PROD0178,14/05/2023,19:32:47,South,Beauty,2,50.00,33.2,...,3.600000,No,Los Angeles,2023-05-14,2023-05-14 19:32:47,2023,5,14,19,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ORD002737,CUST00163,PROD0056,05-14-2022,20:21:10,North,Beauty,10,198.11,5.9,...,1.400000,Yes,Miami,2022-05-14,2022-05-14 20:21:10,2022,5,14,20,1
1816,ORD002192,CUST00327,PROD0096,04-10-2023,06:31:30,North,Toys,1,285.00,36.1,...,3.670571,No,New York,2023-04-10,2023-04-10 06:31:30,2023,4,10,6,0
1817,ORD002209,CUST00420,PROD0037,22/02/2023,15:17:47,East,Clothing,10,66.59,33.1,...,3.800000,No,Phoenix,2023-02-22,2023-02-22 15:17:47,2023,2,22,15,0
1818,ORD002059,CUST00238,PROD0113,13/02/2023,13:03:13,West,Clothing,3,20.00,28.6,...,1.700000,Yes,New York,2023-02-13,2023-02-13 13:03:13,2023,2,13,13,1
1819,ORD001641,CUST00283,PROD0123,2022/06/10,11:46:48,East,Home & Garden,2,347.83,11.8,...,1.200000,No,Atlanta,2022-06-10,2022-06-10 11:46:48,2022,6,10,11,0

## Dropping Duplicates

In [47]:
df['order_id'].duplicated().sum()

70

In [48]:
df[df['order_id'].duplicated()]['order_id']

192     ORD002383
335     ORD001431
408     ORD001971
510     ORD002286
523     ORD002524
          ...
1768    ORD001739
1770    ORD001430
1788    ORD001830
1811    ORD002221
1814    ORD002425
Name: order_id, Length: 70, dtype: object

In [49]:
df[df.duplicated(subset='order_id', keep=False)].sort_values('order_id')

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,...,rating,return_flag,shipping_city,order_date_clean,order_datetime,year,month,day,hour,normalized_return_flag
1204,ORD001071,CUST00533,PROD0117,04/08/2023,20:51:03,East,Clothing,10,127.25,18.5,...,2.7,No,New York,2023-08-04,2023-08-04 20:51:03,2023,8,4,20,0
1723,ORD001071,CUST00533,PROD0117,04/08/2023,20:51:03,East,Clothing,10,127.25,18.5,...,2.7,No,New York,2023-08-04,2023-08-04 20:51:03,2023,8,4,20,0
917,ORD001146,CUST00143,PROD0093,06/08/2023,10:11:10,North,Toys,9,99.70,32.4,...,4.3,No,Miami,2023-08-06,2023-08-06 10:11:10,2023,8,6,10,0
430,ORD001146,CUST00143,PROD0093,06/08/2023,10:11:10,North,Toys,9,99.70,32.4,...,4.3,No,Miami,2023-08-06,2023-08-06 10:11:10,2023,8,6,10,0
1428,ORD001179,CUST00193,PROD0060,05/02/2022,13:38:14,South,Toys,10,82.05,5.4,...,2.4,No,Houston,2022-02-05,2022-02-05 13:38:14,2022,2,5,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,ORD002711,CUST00126,PROD0157,10/02/2023,06:36:34,South,Clothing,7,162.00,0.1,...,4.7,No,Atlanta,2023-02-10,2023-02-10 06:36:34,2023,2,10,6,0
79,ORD002719,CUST00341,PROD0060,12-26-2023,17:33:07,North,Home & Garden,8,259.26,25.1,...,1.7,Yes,Chicago,2023-12-26,2023-12-26 17:33:07,2023,12,26,17,1
1519,ORD002719,CUST00341,PROD0060,12-26-2023,17:33:07,North,Home & Garden,8,259.26,25.1,...,1.7,Yes,Chicago,2023-12-26,2023-12-26 17:33:07,2023,12,26,17,1
661,ORD002725,CUST00001,PROD0140,2023/09/11,17:22:43,North,Beauty,4,367.27,6.4,...,4.1,No,Los Angeles,2023-09-11,2023-09-11 17:22:43,2023,9,11,17,0
490,ORD002725,CUST00001,PROD0140,2023/09/11,17:22:43,North,Beauty,4,367.27,6.4,...,4.1,No,Los Angeles,2023-09-11,2023-09-11 17:22:43,2023,9,11,17,0

In [50]:
df[df.duplicated(subset='order_id', keep=False)]

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,...,rating,return_flag,shipping_city,order_date_clean,order_datetime,year,month,day,hour,normalized_return_flag
28,ORD001431,CUST00424,PROD0084,2023/03/28,08:28:15,East,Electronics,5,248.00,32.7,...,4.1,No,Denver,2023-03-28,2023-03-28 08:28:15,2023,3,28,8,0
36,ORD002294,CUST00459,PROD0188,2023/12/11,07:52:51,East,Books,2,171.67,2.5,...,2.5,No,Miami,2023-12-11,2023-12-11 07:52:51,2023,12,11,7,0
40,ORD002711,CUST00126,PROD0157,10/02/2023,06:36:34,South,Clothing,7,162.00,0.1,...,4.7,No,Atlanta,2023-02-10,2023-02-10 06:36:34,2023,2,10,6,0
58,ORD001883,CUST00226,PROD0190,02-27-2023,12:43:49,North,Clothing,2,157.42,24.2,...,4.4,No,Los Angeles,2023-02-27,2023-02-27 12:43:49,2023,2,27,12,0
79,ORD002719,CUST00341,PROD0060,12-26-2023,17:33:07,North,Home & Garden,8,259.26,25.1,...,1.7,Yes,Chicago,2023-12-26,2023-12-26 17:33:07,2023,12,26,17,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1768,ORD001739,CUST00160,PROD0142,08-17-2023,16:30:15,West,Beuaty,10,329.90,5.5,...,4.0,No,New York,2023-08-17,2023-08-17 16:30:15,2023,8,17,16,0
1770,ORD001430,CUST00516,PROD0121,08-28-2022,21:46:37,East,Beauty,2,116.85,27.5,...,4.8,No,Dallas,2022-08-28,2022-08-28 21:46:37,2022,8,28,21,0
1788,ORD001830,CUST00212,PROD0027,2022/10/03,19:10:40,West,Sports,2,136.58,22.0,...,1.1,No,Miami,2022-10-03,2022-10-03 19:10:40,2022,10,3,19,0
1811,ORD002221,CUST00227,PROD0125,2023/01/02,22:44:50,East,Electronics,9,576.00,23.5,...,3.7,Yes,Dallas,2023-01-02,2023-01-02 22:44:50,2023,1,2,22,1
1814,ORD002425,CUST00235,PROD0079,2022/03/23,07:10:23,North,Beauty,10,106.53,11.1,...,1.4,No,Los Angeles,2022-03-23,2022-03-23 07:10:23,2022,3,23,7,0

In [51]:
df['order_id'].duplicated().sum()

70

In [52]:
df = df.drop_duplicates(subset='order_id', keep='first')

In [53]:
df['order_id'].duplicated().sum()

0

## Creating Revenue Column

In [54]:
df['revenue'] = df['quantity'] * df['unit_price'] * (1 - df['discount_pct']/100)

C:\Users\DELL\AppData\Local\Temp\ipykernel_8224\2104199291.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['revenue'] = df['quantity'] * df['unit_price'] * (1 - df['discount_pct']/100)

In [55]:
df

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,...,return_flag,shipping_city,order_date_clean,order_datetime,year,month,day,hour,normalized_return_flag,revenue
0,ORD001382,CUST00230,PROD0156,10-17-2022,22:51:03,West,Beauty,9,399.15,7.8,...,No,Dallas,2022-10-17,2022-10-17 22:51:03,2022,10,17,22,0,3312.14670
1,ORD001002,CUST00176,PROD0197,24/09/2023,13:43:20,Central,Home & Garden,8,105.48,16.0,...,Yes,Phoenix,2023-09-24,2023-09-24 13:43:20,2023,9,24,13,1,708.82560
2,ORD002682,CUST00138,PROD0103,2022/11/01,08:34:16,East,Electronics,4,587.89,37.5,...,No,Miami,2022-11-01,2022-11-01 08:34:16,2022,11,1,8,0,1469.72500
3,ORD002322,Unknown,PROD0178,10-02-2023,13:36:06,Central,Home & Garden,5,198.49,28.6,...,No,Phoenix,2023-10-02,2023-10-02 13:36:06,2023,10,2,13,0,708.60930
4,ORD001669,CUST00188,PROD0178,14/05/2023,19:32:47,South,Beauty,2,50.00,33.2,...,No,Los Angeles,2023-05-14,2023-05-14 19:32:47,2023,5,14,19,0,66.80000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ORD002737,CUST00163,PROD0056,05-14-2022,20:21:10,North,Beauty,10,198.11,5.9,...,Yes,Miami,2022-05-14,2022-05-14 20:21:10,2022,5,14,20,1,1864.21510
1816,ORD002192,CUST00327,PROD0096,04-10-2023,06:31:30,North,Toys,1,285.00,36.1,...,No,New York,2023-04-10,2023-04-10 06:31:30,2023,4,10,6,0,182.11500
1817,ORD002209,CUST00420,PROD0037,22/02/2023,15:17:47,East,Clothing,10,66.59,33.1,...,No,Phoenix,2023-02-22,2023-02-22 15:17:47,2023,2,22,15,0,445.48710
1818,ORD002059,CUST00238,PROD0113,13/02/2023,13:03:13,West,Clothing,3,20.00,28.6,...,Yes,New York,2023-02-13,2023-02-13 13:03:13,2023,2,13,13,1,42.84000
1819,ORD001641,CUST00283,PROD0123,2022/06/10,11:46:48,East,Home & Garden,2,347.83,11.8,...,No,Atlanta,2022-06-10,2022-06-10 11:46:48,2022,6,10,11,0,613.57212

## Creating Age_group Column

In [56]:
df['age_group'] = pd.cut(df['customer_age'],
                        bins=[0,18,35,50,70],
                        labels=['Teen','Young Adult','Adult','Senior'])

C:\Users\DELL\AppData\Local\Temp\ipykernel_8224\1553303141.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age_group'] = pd.cut(df['customer_age'],

In [57]:
df

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,...,shipping_city,order_date_clean,order_datetime,year,month,day,hour,normalized_return_flag,revenue,age_group
0,ORD001382,CUST00230,PROD0156,10-17-2022,22:51:03,West,Beauty,9,399.15,7.8,...,Dallas,2022-10-17,2022-10-17 22:51:03,2022,10,17,22,0,3312.14670,Young Adult
1,ORD001002,CUST00176,PROD0197,24/09/2023,13:43:20,Central,Home & Garden,8,105.48,16.0,...,Phoenix,2023-09-24,2023-09-24 13:43:20,2023,9,24,13,1,708.82560,Adult
2,ORD002682,CUST00138,PROD0103,2022/11/01,08:34:16,East,Electronics,4,587.89,37.5,...,Miami,2022-11-01,2022-11-01 08:34:16,2022,11,1,8,0,1469.72500,Adult
3,ORD002322,Unknown,PROD0178,10-02-2023,13:36:06,Central,Home & Garden,5,198.49,28.6,...,Phoenix,2023-10-02,2023-10-02 13:36:06,2023,10,2,13,0,708.60930,NaN
4,ORD001669,CUST00188,PROD0178,14/05/2023,19:32:47,South,Beauty,2,50.00,33.2,...,Los Angeles,2023-05-14,2023-05-14 19:32:47,2023,5,14,19,0,66.80000,Senior
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ORD002737,CUST00163,PROD0056,05-14-2022,20:21:10,North,Beauty,10,198.11,5.9,...,Miami,2022-05-14,2022-05-14 20:21:10,2022,5,14,20,1,1864.21510,Senior
1816,ORD002192,CUST00327,PROD0096,04-10-2023,06:31:30,North,Toys,1,285.00,36.1,...,New York,2023-04-10,2023-04-10 06:31:30,2023,4,10,6,0,182.11500,Senior
1817,ORD002209,CUST00420,PROD0037,22/02/2023,15:17:47,East,Clothing,10,66.59,33.1,...,Phoenix,2023-02-22,2023-02-22 15:17:47,2023,2,22,15,0,445.48710,NaN
1818,ORD002059,CUST00238,PROD0113,13/02/2023,13:03:13,West,Clothing,3,20.00,28.6,...,New York,2023-02-13,2023-02-13 13:03:13,2023,2,13,13,1,42.84000,Senior
1819,ORD001641,CUST00283,PROD0123,2022/06/10,11:46:48,East,Home & Garden,2,347.83,11.8,...,Atlanta,2022-06-10,2022-06-10 11:46:48,2022,6,10,11,0,613.57212,Senior

In [58]:
print(df)

       order_id customer_id product_id  order_date order_time   region  \
0     ORD001382   CUST00230   PROD0156  10-17-2022   22:51:03     West
1     ORD001002   CUST00176   PROD0197  24/09/2023   13:43:20  Central
2     ORD002682   CUST00138   PROD0103  2022/11/01   08:34:16     East
3     ORD002322     Unknown   PROD0178  10-02-2023   13:36:06  Central
4     ORD001669   CUST00188   PROD0178  14/05/2023   19:32:47    South
...         ...         ...        ...         ...        ...      ...
1815  ORD002737   CUST00163   PROD0056  05-14-2022   20:21:10    North
1816  ORD002192   CUST00327   PROD0096  04-10-2023   06:31:30    North
1817  ORD002209   CUST00420   PROD0037  22/02/2023   15:17:47     East
1818  ORD002059   CUST00238   PROD0113  13/02/2023   13:03:13     West
1819  ORD001641   CUST00283   PROD0123  2022/06/10   11:46:48     East

           category  quantity  unit_price  discount_pct  ... shipping_city  \
0            Beauty         9      399.15           7.8  ...        Dallas
1     Home & Garden         8      105.48          16.0  ...       Phoenix
2       Electronics         4      587.89          37.5  ...         Miami
3     Home & Garden         5      198.49          28.6  ...       Phoenix
4            Beauty         2       50.00          33.2  ...   Los Angeles
...             ...       ...         ...           ...  ...           ...
1815         Beauty        10      198.11           5.9  ...         Miami
1816           Toys         1      285.00          36.1  ...      New York
1817       Clothing        10       66.59          33.1  ...       Phoenix
1818       Clothing         3       20.00          28.6  ...      New York
1819  Home & Garden         2      347.83          11.8  ...       Atlanta

      order_date_clean      order_datetime  year month day hour  \
0           2022-10-17 2022-10-17 22:51:03  2022    10  17   22
1           2023-09-24 2023-09-24 13:43:20  2023     9  24   13
2           2022-11-01 2022-11-01 08:34:16  2022    11   1    8
3           2023-10-02 2023-10-02 13:36:06  2023    10   2   13
4           2023-05-14 2023-05-14 19:32:47  2023     5  14   19
...                ...                 ...   ...   ...  ..  ...
1815        2022-05-14 2022-05-14 20:21:10  2022     5  14   20
1816        2023-04-10 2023-04-10 06:31:30  2023     4  10    6
1817        2023-02-22 2023-02-22 15:17:47  2023     2  22   15
1818        2023-02-13 2023-02-13 13:03:13  2023     2  13   13
1819        2022-06-10 2022-06-10 11:46:48  2022     6  10   11

      normalized_return_flag     revenue    age_group
0                          0  3312.14670  Young Adult
1                          1   708.82560        Adult
2                          0  1469.72500        Adult
3                          0   708.60930          NaN
4                          0    66.80000       Senior
...                      ...         ...          ...
1815                       1  1864.21510       Senior
1816                       0   182.11500       Senior
1817                       0   445.48710          NaN
1818                       1    42.84000       Senior
1819                       0   613.57212       Senior

[1750 rows x 24 columns]

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1750 entries, 0 to 1819
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                1750 non-null   object
 1   customer_id             1750 non-null   object
 2   product_id              1750 non-null   object
 3   order_date              1750 non-null   object
 4   order_time              1750 non-null   object
 5   region                  1750 non-null   object
 6   category                1750 non-null   object
 7   quantity                1750 non-null   int64
 8   unit_price              1750 non-null   float64
 9   discount_pct            1750 non-null   float64
 10  payment_method          1750 non-null   object
 11  customer_age            1750 non-null   float64
 12  rating                  1750 non-null   float64
 13  return_flag             1750 non-null   object
 14  shipping_city           1750 non-null   object
 15  order_date_clean        1750 non-null   datetime64[ns]
 16  order_datetime          1750 non-null   datetime64[ns]
 17  year                    1750 non-null   int32
 18  month                   1750 non-null   int32
 19  day                     1750 non-null   int32
 20  hour                    1750 non-null   int32
 21  normalized_return_flag  1750 non-null   int64
 22  revenue                 1750 non-null   float64
 23  age_group               1536 non-null   category
dtypes: category(1), datetime64[ns](2), float64(5), int32(4), int64(2), object(10)
memory usage: 302.7+ KB

In [69]:
df['customer_age'].head(30)

0      35.0
1      38.0
2      44.0
3      72.0
4      52.0
5      37.0
6      47.0
7      55.0
8      47.0
9      24.0
10     30.0
11    150.0
12     73.0
13     30.0
14     70.0
15     26.0
16     72.0
17     32.0
18     50.0
19     -5.0
20     40.0
21     26.0
22     29.0
23     32.0
24     49.0
25     47.0
26     59.0
27     42.0
28     51.0
29     25.0
Name: customer_age, dtype: float64

## Handling Customer_age Outliers

In [70]:
df['customer_age'] = df['customer_age'].replace({
    -5.0: 50.0,
    200.0: 20.0,
    150.0: 15.0
})

C:\Users\DELL\AppData\Local\Temp\ipykernel_8224\4120972331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['customer_age'] = df['customer_age'].replace({

In [71]:
df['customer_age'].head(30)

0     35.0
1     38.0
2     44.0
3     72.0
4     52.0
5     37.0
6     47.0
7     55.0
8     47.0
9     24.0
10    30.0
11    15.0
12    73.0
13    30.0
14    70.0
15    26.0
16    72.0
17    32.0
18    50.0
19    50.0
20    40.0
21    26.0
22    29.0
23    32.0
24    49.0
25    47.0
26    59.0
27    42.0
28    51.0
29    25.0
Name: customer_age, dtype: float64

In [72]:
df['customer_age'] = df['customer_age'].round().astype(int)

C:\Users\DELL\AppData\Local\Temp\ipykernel_8224\3246913232.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['customer_age'] = df['customer_age'].round().astype(int)

In [73]:
df['customer_age'].head(30)

0     35
1     38
2     44
3     72
4     52
5     37
6     47
7     55
8     47
9     24
10    30
11    15
12    73
13    30
14    70
15    26
16    72
17    32
18    50
19    50
20    40
21    26
22    29
23    32
24    49
25    47
26    59
27    42
28    51
29    25
Name: customer_age, dtype: int32

In [74]:
df['age_group'] = pd.cut(
    df['customer_age'],
    bins=[0, 18, 35, 50, 70, 120],
    labels=['Teen', 'Young Adult', 'Adult', 'Middle Age', 'Senior']
)

C:\Users\DELL\AppData\Local\Temp\ipykernel_8224\2259882048.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age_group'] = pd.cut(

In [75]:
df[['customer_age', 'age_group']].head(30)

    customer_age    age_group
0             35  Young Adult
1             38        Adult
2             44        Adult
3             72       Senior
4             52   Middle Age
5             37        Adult
6             47        Adult
7             55   Middle Age
8             47        Adult
9             24  Young Adult
10            30  Young Adult
11            15         Teen
12            73       Senior
13            30  Young Adult
14            70   Middle Age
15            26  Young Adult
16            72       Senior
17            32  Young Adult
18            50        Adult
19            50        Adult
20            40        Adult
21            26  Young Adult
22            29  Young Adult
23            32  Young Adult
24            49        Adult
25            47        Adult
26            59   Middle Age
27            42        Adult
28            51   Middle Age
29            25  Young Adult

In [76]:
df.head(30)

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,...,shipping_city,order_date_clean,order_datetime,year,month,day,hour,normalized_return_flag,revenue,age_group
0,ORD001382,CUST00230,PROD0156,10-17-2022,22:51:03,West,Beauty,9,399.15,7.8,...,Dallas,2022-10-17,2022-10-17 22:51:03,2022,10,17,22,0,3312.14670,Young Adult
1,ORD001002,CUST00176,PROD0197,24/09/2023,13:43:20,Central,Home & Garden,8,105.48,16.0,...,Phoenix,2023-09-24,2023-09-24 13:43:20,2023,9,24,13,1,708.82560,Adult
2,ORD002682,CUST00138,PROD0103,2022/11/01,08:34:16,East,Electronics,4,587.89,37.5,...,Miami,2022-11-01,2022-11-01 08:34:16,2022,11,1,8,0,1469.72500,Adult
3,ORD002322,Unknown,PROD0178,10-02-2023,13:36:06,Central,Home & Garden,5,198.49,28.6,...,Phoenix,2023-10-02,2023-10-02 13:36:06,2023,10,2,13,0,708.60930,Senior
4,ORD001669,CUST00188,PROD0178,14/05/2023,19:32:47,South,Beauty,2,50.00,33.2,...,Los Angeles,2023-05-14,2023-05-14 19:32:47,2023,5,14,19,0,66.80000,Middle Age
5,ORD002153,CUST00220,PROD0144,2022/04/12,19:32:03,West,Beuaty,8,319.79,39.5,...,Miami,2022-04-12,2022-04-12 19:32:03,2022,4,12,19,0,1547.78360,Adult
6,ORD001917,CUST00063,PROD0004,07-22-2023,16:19:57,East,Beauty,3,365.82,11.6,...,Denver,2023-07-22,2023-07-22 16:19:57,2023,7,22,16,0,970.15464,Adult
7,ORD002116,CUST00354,PROD0076,2022/04/02,18:07:30,East,Beauty,5,47.33,36.3,...,Phoenix,2022-04-02,2022-04-02 18:07:30,2022,4,2,18,0,150.74605,Middle Age
8,ORD002046,CUST00257,PROD0179,2022/08/16,06:51:44,North,Beauty,9,223.51,31.0,...,Atlanta,2022-08-16,2022-08-16 06:51:44,2022,8,16,6,0,1387.99710,Adult
9,ORD001495,CUST00503,PROD0022,13/01/2022,02:34:05,West,Sports,8,25.08,18.2,...,New York,2022-01-13,2022-01-13 02:34:05,2022,1,13,2,0,164.12352,Young Adult
10,ORD002304,CUST00073,PROD0137,25/04/2023,21:35:13,North,Toys,5,50.00,0.9,...,Houston,2023-04-25,2023-04-25 21:35:13,2023,4,25,21,1,247.75000,Young Adult
11,ORD001111,CUST00505,PROD0019,07-12-2023,13:10:28,South,Toys,2,222.95,38.1,...,Miami,2023-07-12,2023-07-12 13:10:28,2023,7,12,13,0,276.01210,Teen
12,ORD001654,CUST00181,PROD0185,2023/12/01,13:22:08,South,Electronics,3,753.05,26.4,...,Houston,2023-12-01,2023-12-01 13:22:08,2023,12,1,13,0,1662.73440,Senior
13,ORD001292,CUST00553,PROD0114,01-22-2023,22:20:11,East,Sports,4,395.47,2.1,...,Houston,2023-01-22,2023-01-22 22:20:11,2023,1,22,22,0,1548.66052,Young Adult
14,ORD002402,CUST00271,PROD0082,19/02/2023,16:19:57,South,Books,1,357.63,0.2,...,Chicago,2023-02-19,2023-02-19 16:19:57,2023,2,19,16,0,356.91474,Middle Age
15,ORD001742,CUST00387,PROD0141,2022/11/07,16:13:46,East,Electronics,2,241.07,14.3,...,Seattle,2022-11-07,2022-11-07 16:13:46,2022,11,7,16,0,413.19398,Young Adult
16,ORD001937,CUST00568,PROD0195,11/07/2023,18:29:22,East,Sports,9,150.79,3.9,...,Houston,2023-07-11,2023-07-11 18:29:22,2023,7,11,18,0,1304.18271,Senior
17,ORD001711,CUST00430,PROD0068,2023/01/06,11:02:59,North,Spoorts,7,222.53,35.8,...,Chicago,2023-01-06,2023-01-06 11:02:59,2023,1,6,11,0,1000.04982,Young Adult
18,ORD002504,CUST00032,PROD0181,03/09/2023,11:58:13,South,Books,1,45.79,1.2,...,Denver,2023-09-03,2023-09-03 11:58:13,2023,9,3,11,0,45.24052,Adult
19,ORD001158,CUST00261,PROD0143,2022/08/27,17:23:35,North,Books,8,255.65,14.0,...,Denver,2022-08-27,2022-08-27 17:23:35,2022,8,27,17,0,1758.87200,Adult
20,ORD002317,CUST00389,PROD0057,03-10-2023,15:20:30,South,Sports,1,118.21,2.2,...,Denver,2023-03-10,2023-03-10 15:20:30,2023,3,10,15,0,115.60938,Adult
21,ORD002353,CUST00067,PROD0072,02-23-2022,07:05:39,South,Beauty,8,228.51,16.0,...,Atlanta,2022-02-23,2022-02-23 07:05:39,2022,2,23,7,0,1535.58720,Young Adult
22,ORD002592,CUST00177,PROD0128,06/04/2023,15:22:20,North,Toys,9,326.25,32.4,...,New York,2023-04-06,2023-04-06 15:22:20,2023,4,6,15,0,1984.90500,Young Adult
23,ORD001972,CUST00245,PROD0171,08-13-2022,20:29:55,West,Beauty,2,227.86,12.4,...,Phoenix,2022-08-13,2022-08-13 20:29:55,2022,8,13,20,1,399.21072,Young Adult
24,ORD002546,CUST00420,PROD0104,10/03/2022,06:39:16,South,Books,10,277.09,18.1,...,Chicago,2022-03-10,2022-03-10 06:39:16,2022,3,10,6,0,2269.36710,Adult
25,ORD002008,CUST00462,PROD0099,01-17-2023,07:51:57,East,Beauty,1,150.85,21.1,...,Miami,2023-01-17,2023-01-17 07:51:57,2023,1,17,7,0,119.02065,Adult
26,ORD001217,CUST00555,PROD0006,03-16-2023,15:12:04,East,Sports,8,145.00,13.4,...,Phoenix,2023-03-16,2023-03-16 15:12:04,2023,3,16,15,0,1004.56000,Middle Age
27,ORD002714,CUST00552,PROD0107,2022/03/16,10:56:08,North,Sports,1,190.58,0.0,...,Chicago,2022-03-16,2022-03-16 10:56:08,2022,3,16,10,0,190.58000,Adult
28,ORD001431,CUST00424,PROD0084,2023/03/28,08:28:15,East,Electronics,5,248.00,32.7,...,Denver,2023-03-28,2023-03-28 08:28:15,2023,3,28,8,0,834.52000,Middle Age
29,ORD001594,Unknown,PROD0071,15/01/2023,15:23:33,South,Sports,6,287.92,28.2,...,Dallas,2023-01-15,2023-01-15 15:23:33,2023,1,15,15,0,1240.35936,Young Adult

In [77]:
df

,order_id,customer_id,product_id,order_date,order_time,region,category,quantity,unit_price,discount_pct,...,shipping_city,order_date_clean,order_datetime,year,month,day,hour,normalized_return_flag,revenue,age_group
0,ORD001382,CUST00230,PROD0156,10-17-2022,22:51:03,West,Beauty,9,399.15,7.8,...,Dallas,2022-10-17,2022-10-17 22:51:03,2022,10,17,22,0,3312.14670,Young Adult
1,ORD001002,CUST00176,PROD0197,24/09/2023,13:43:20,Central,Home & Garden,8,105.48,16.0,...,Phoenix,2023-09-24,2023-09-24 13:43:20,2023,9,24,13,1,708.82560,Adult
2,ORD002682,CUST00138,PROD0103,2022/11/01,08:34:16,East,Electronics,4,587.89,37.5,...,Miami,2022-11-01,2022-11-01 08:34:16,2022,11,1,8,0,1469.72500,Adult
3,ORD002322,Unknown,PROD0178,10-02-2023,13:36:06,Central,Home & Garden,5,198.49,28.6,...,Phoenix,2023-10-02,2023-10-02 13:36:06,2023,10,2,13,0,708.60930,Senior
4,ORD001669,CUST00188,PROD0178,14/05/2023,19:32:47,South,Beauty,2,50.00,33.2,...,Los Angeles,2023-05-14,2023-05-14 19:32:47,2023,5,14,19,0,66.80000,Middle Age
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ORD002737,CUST00163,PROD0056,05-14-2022,20:21:10,North,Beauty,10,198.11,5.9,...,Miami,2022-05-14,2022-05-14 20:21:10,2022,5,14,20,1,1864.21510,Middle Age
1816,ORD002192,CUST00327,PROD0096,04-10-2023,06:31:30,North,Toys,1,285.00,36.1,...,New York,2023-04-10,2023-04-10 06:31:30,2023,4,10,6,0,182.11500,Middle Age
1817,ORD002209,CUST00420,PROD0037,22/02/2023,15:17:47,East,Clothing,10,66.59,33.1,...,Phoenix,2023-02-22,2023-02-22 15:17:47,2023,2,22,15,0,445.48710,Senior
1818,ORD002059,CUST00238,PROD0113,13/02/2023,13:03:13,West,Clothing,3,20.00,28.6,...,New York,2023-02-13,2023-02-13 13:03:13,2023,2,13,13,1,42.84000,Middle Age
1819,ORD001641,CUST00283,PROD0123,2022/06/10,11:46:48,East,Home & Garden,2,347.83,11.8,...,Atlanta,2022-06-10,2022-06-10 11:46:48,2022,6,10,11,0,613.57212,Middle Age

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1750 entries, 0 to 1819
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                1750 non-null   object
 1   customer_id             1750 non-null   object
 2   product_id              1750 non-null   object
 3   order_date              1750 non-null   object
 4   order_time              1750 non-null   object
 5   region                  1750 non-null   object
 6   category                1750 non-null   object
 7   quantity                1750 non-null   int64
 8   unit_price              1750 non-null   float64
 9   discount_pct            1750 non-null   float64
 10  payment_method          1750 non-null   object
 11  customer_age            1750 non-null   int32
 12  rating                  1750 non-null   float64
 13  return_flag             1750 non-null   object
 14  shipping_city           1750 non-null   object
 15  order_date_clean        1750 non-null   datetime64[ns]
 16  order_datetime          1750 non-null   datetime64[ns]
 17  year                    1750 non-null   int32
 18  month                   1750 non-null   int32
 19  day                     1750 non-null   int32
 20  hour                    1750 non-null   int32
 21  normalized_return_flag  1750 non-null   int64
 22  revenue                 1750 non-null   float64
 23  age_group               1739 non-null   category
dtypes: category(1), datetime64[ns](2), float64(4), int32(5), int64(2), object(10)
memory usage: 295.9+ KB

In [81]:
df.describe()

,quantity,unit_price,discount_pct,customer_age,rating,order_date_clean,order_datetime,year,month,day,hour,normalized_return_flag,revenue
count,1750.000000,1750.000000,1750.000000,1750.000000,1750.000000,1750,1750,1750.000000,1750.000000,1750.000000,1750.000000,1750.000000,1750.000000
mean,5.482286,332.225354,18.843429,46.365714,3.645216,2022-12-15 10:23:43.542856960,2022-12-16 00:13:14.798857216,2022.472571,6.370286,14.382286,13.320000,0.151429,1385.784576
min,1.000000,10.220000,0.000000,0.000000,-1.000000,2022-01-01 00:00:00,2022-01-01 00:31:15,2022.000000,1.000000,1.000000,0.000000,0.000000,10.606300
25%,3.000000,102.362500,9.000000,32.000000,2.000000,2022-06-11 00:00:00,2022-06-11 10:11:24.249999872,2022.000000,3.000000,7.000000,9.000000,0.000000,276.037125
50%,5.500000,198.505000,18.200000,47.000000,3.000000,2022-12-07 00:00:00,2022-12-07 10:20:54,2022.000000,6.000000,14.000000,13.000000,0.000000,728.733180
75%,8.000000,321.402500,29.175000,61.000000,3.900000,2023-06-21 00:00:00,2023-06-21 17:00:22.500000,2023.000000,9.000000,22.000000,18.000000,0.000000,1491.676890
max,10.000000,15000.000000,40.000000,75.000000,99.000000,2023-12-28 00:00:00,2023-12-28 20:06:48,2023.000000,12.000000,28.000000,22.000000,1.000000,89599.910400
std,2.878416,1087.847899,11.772067,17.220063,8.023243,NaN,NaN,0.499390,3.454685,8.167740,5.501951,0.358569,4003.231782

In [79]:
df.isnull().sum()

order_id                   0
customer_id                0
product_id                 0
order_date                 0
order_time                 0
region                     0
category                   0
quantity                   0
unit_price                 0
discount_pct               0
payment_method             0
customer_age               0
rating                     0
return_flag                0
shipping_city              0
order_date_clean           0
order_datetime             0
year                       0
month                      0
day                        0
hour                       0
normalized_return_flag     0
revenue                    0
age_group                 11
dtype: int64

## Exporting Dataset

In [82]:
df.to_csv('ecommerce.csv', index=False)